### PR TITLE
Multiple updates

### PR DESCRIPTION
**Pull request by jandress**
Fix exec perm issues, update build env doc, add ova and images for build environment

### CODE REVIEW

**Review by 0x48piraj — COMMENTED** [review]
We're going to include the virtual appliance (.ova) files as well ?

**Comment by scriptingxss** [comment]
> We're going to include the virtual appliance (.ova) files as well ?

Yes, as a baseline fresh image/fork from this repo. I think we will need to push this PR to a develop branch for testing.

**Comment by 0x48piraj** [comment]
A development branch would be great!

**Comment by scriptingxss** [comment]
Develop branch created - https://github.com/scriptingxss/IoTGoat/tree/Develop. Please resubmit this PR.

**Pull request closed without merging**
