### PR TITLE
New /etc/banner

### PR DESCRIPTION
**Pull request by 0x48piraj**
#### Changes :

* New `/etc/banner` ASCII Art

#### Screenshot :

> **(built using openwrt image-builder with this change)**

image

### CODE REVIEW

**Comment by 0x48piraj** [comment]
Ping @scriptingxss

**Comment by cldrn** [comment]
I agree we need a banner. Although there is so much potential for goats in ascii I'm not sure we would be taking full advantage with this one.

**Comment by 0x48piraj** [comment]
Found a resource : http://www.oocities.org/spunk1111/farm.htm#goat

Should I implement one into our banner ?

**Comment by 0x48piraj** [comment]
```
                                                           .--,\\\__         
 ██████╗ ██╗    ██╗ █████╗ ███████╗██████╗                  `-.    a`-.__    
██╔═══██╗██║    ██║██╔══██╗██╔════╝██╔══██╗                   |         ')   
██║   ██║██║ █╗ ██║███████║███████╗██████╔╝                  / \ _.-'-,`;    
██║   ██║██║███╗██║██╔══██║╚════██║██╔═══╝                  /     |   { /    
╚██████╔╝╚███╔███╔╝██║  ██║███████║██║                      /     |   { /    
 ╚═════╝  ╚══╝╚══╝ ╚═╝  ╚═╝╚══════╝╚═╝            ..-"``~"-'      ;    )     
                                           ╦┌─┐╔╦╗╔═╗┌─┐┌─┐┌┬┐   ;'    `     
                                           ║│ │ ║ ║ ╦│ │├─┤ │   ;'    `      
                                           ╩└─┘ ╩ ╚═╝└─┘┴ ┴ ┴  ;'    `       
 ------------------------------------------------------------ ;'             
 Firmware [info] :  %D %V, %C                                                
 ------------------------------------------------------------                
```
How is it now @cldrn ?

> Ping @scriptingxss

**Pull request merged**
