### PR TITLE
I1, I7 & I3 Challenges

### PR DESCRIPTION
**Pull request by 0x48piraj**
#### Changes

- Fixed `rc.local`, wrote boot scripts
- Init `passwd`, `shadow` files for `iotgoat` and `root` user accounts
- Pushed vulnerable API directory to `/vulnapi`
- Implemented vulnerable login & OS command injection challenges
- Implemented hard-coded encryption key to `/etc/dropbear` under `/keys`

### CODE REVIEW

**Comment by scriptingxss** [comment]
/etc/shadow overwrites the already created hardcoded password. 

Curious to know that file size of the compiled image with both php, python, and Django. I applaud the idea of including an already vulnerable API to ease development efforts although there is no context how this relates to IoT Security. From the tiredful-api documentation it appears the API is based on a book store, ads, and a blog? Perhaps the theme can be modified to a more applicable subject?

**Comment by 0x48piraj** [comment]
Yes, it overwrites the file because the root password was changed to a password that can be bruteforced using a famous word-list named **darkc0de.lst**

And, the tiredful-api was used as in a router, generally there's no REST API, but, I was said to implement one.

**Comment by scriptingxss** [comment]
Could you share the updated password out of band?

What are the router use cases in the API?

**Comment by 0x48piraj** [comment]
Done

**Comment by scriptingxss** [comment]
Closed this PR. Not enough information on the  API, passwords, or the file size of the compiled firmware with php, python, and Django framework.

**Pull request closed without merging**
